### ISSUE TITLE
Respect .config and .home

### ISSUE THREAD

**Issue by izzylaif** [area-of-dev/Telegram.AppImage#1]
Telegram.AppImage creates TelegramDesktop folder in /home/user/.local/share even if Telegram.AppImage.local folder is present near Telegram.AppImage.
AppImages are supposed to store data in Telegram.AppImage.local and Telegram.AppImage.config folders if they exist in the same folder as Telegram.AppImage to make the applications portable.

**Comment by AlexWoroschilow** [comment]
Hi izzylaif, 

i am not a developer of the TelegramDesktop app, please create a feature request here:
https://github.com/telegramdesktop/tdesktop

you can also ask the guys to provide an official AppImage
